[tasks.clean]
command = "rm"
args = ["-rf", "./build", "./Move.lock"]

[tasks.build]
command = "sui"
args = ["move", "build"]

[tasks.adds]
command = "sui"
args = ["client", "addresses"]

[tasks.publish]
command = "sui"
args = ["client", "publish", "--gas-budget", "3000000000"]

# active address
[tasks.active]
command = "sui"
args = ["client", "active-address"]

[tasks.gas]
dependencies = ["active"]
command = "zsh"
args = ["-c", "ADDR=$(avtive) sui client gas $ADDR"]

[tasks.objs]
command = "sui"
args = ["client", "objects"]

[tasks.obj]
script = """
sui client object $@
"""